baseURL: 'https://vedanet.uehr.co/'
languageCode: 'ja'
title: 'vedanet'
theme: 'PaperMod'
publishDir: "docs"
params:
    assets:
        favicon: "/favicon.ico"
        favicon16x16:  "/images/favicon-16x16.png"
        favicon32x32:  "/images/favicon-32x32.png"
        apple_touch_icon:  "/images/apple-touch-icon.png"
    images: "vedanet.png"
    ShareButtons: ["twitter"]