baseURL: 'https://pao.uehr.co/'
languageCode: 'ja'
title: 'PAO'
theme: 'PaperMod'
publishDir: "docs"
params:
    defaultTheme: light
    assets:
        favicon: "/favicon.ico"
        favicon16x16:  "/images/favicon-16x16.png"
        favicon32x32:  "/images/favicon-32x32.png"
        apple_touch_icon:  "/images/apple-touch-icon.png"
    images: ["images/koibana-ai/koibana-ai-ogp.png"]
    ShowShareButtons: true
    ShareButtons: ["line", "twitter", "facebook"]
    DateFormat: "2006-01-02"